### ISSUE TITLE
Error bootstrapping requirements

### ISSUE THREAD

**Issue by manuelbcd** [sysdiglabs/gcp-workshop-sysdig#2]
```
Help Token: AT7i-rGDZ8ILwU   ...  YThAp2xO7zjEj
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - subject: ?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=mateo-burillo-ns
    type: googleapis.com
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: serviceusage.googleapis.com
  metadata:
    permission: serviceusage.services.enable
    resource: mateo...ns
    service: serviceusage.googleapis.com
  reason: AUTH_PERMISSION_DENIED
```
